### ISSUE TITLE
Rendering issues involving meshes without culling

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_editor#5] opened 2022-06-11 18:47 UTC
![image](https://user-images.githubusercontent.com/6856627/173200925-8c2b5248-ce68-4ee6-9d37-6e1ffa62d012.png)
![image](https://user-images.githubusercontent.com/6856627/173200941-72499609-8363-4187-8f14-3386b5f569fe.png)
I knew I'd face some issues rendering my Paper Mario mod. It seems that rendering the backsides of faces has bloom applied even though it should be flat shading. The second image (the front faces) show what it should look like.

**Comment by ScanMountGoat** [comment] 2022-06-15 20:52
Do you have a link to the model files for testing this?

**Comment by ScanMountGoat** [comment] 2022-06-23 20:30
@zrksyd Do you have screenshots from in game of what this is supposed to look like?

**Comment by zrksyd** [comment] 2022-06-30 02:20
[No_Culling_Example.zip](https://github.com/ScanMountGoat/ssbh_editor/files/9015875/No_Culling_Example.zip)
I can't get screenshots of what it's supposed to look like, but it should be as bright / dark as the second image on both sides.

**Comment by ScanMountGoat** [comment] 2022-07-02 01:26
The issue is with specular lighting rather than with bloom. Bloom is pretty subtle even in this case. The issue will be fixed for the next release.

**Closed** 2022-07-03 22:35 UTC
Labels: bug, ssbh_wgpu
