### ISSUE TITLE
Incorrect skinning in game after resaving numshb (Joker)

### ISSUE THREAD

**Issue by LargeLeader** [ScanMountGoat/ssbh_editor#78] opened 2022-08-17 22:22 UTC
Unsure how else to explain it. I attempted to rename face meshes for my model so they wouldn't be impacted by the expressions switching (eg face_mouth_result>mouth). After making the change and also adjusting the numdlb and numatb to make sure that the correct object names correspond with the correct materials, I attempted to check in-game which resulted in the following:
![image](https://user-images.githubusercontent.com/74743796/185253852-8aac5558-38a2-4ab1-9b5f-ba6fe6f9f60d.png)
It looks and animates perfectly in SSBH Editor. I rolled back to an older version of the model before those changes and it works fine
![7C2W8MV](https://user-images.githubusercontent.com/74743796/185253934-9b78dbf5-c412-4d04-86ea-461cb6b42dcf.png)

I can provide files on discord if this requires further diagnosing.

**Comment by ScanMountGoat** [comment] 2022-08-17 22:39
Are the subindex values unique for each mesh object with the same name? You'll need to toggle advanced settings to see it. I'll make a note to add this as a validation error since this can also happen older versions of the Blender addon.

**Comment by LargeLeader** [comment] 2022-08-17 23:50
I had to access advanced settings to change the names but I did not look to see any information regarding subindex values. I can take a look at it and will send info

**Comment by LargeLeader** [comment] 2022-08-18 13:35
I attempted to go into advanced settings for the numdlb, nushmb, and numatb to see if I could find a column related to subindex values but never saw it. I imagine I'm looking in the wrong place for that. Mind if I send the files to you on discord?

**Comment by ScanMountGoat** [comment] 2022-08-18 13:38
Sending the files on discord is fine. There should be a subindex column if you click the model.numshb and enable advanced settings. The material assignments may also be messed up, which can be fixed by editing the model.numdlb.

**Comment by ScanMountGoat** [comment] 2022-08-20 17:08
This is caused by https://github.com/ultimate-research/ssbh_lib/issues/138

**Comment by ScanMountGoat** [comment] 2022-08-20 17:15
Until this is fixed, please use https://github.com/ultimate-research/ssbh_lib/releases for renaming meshes. This issue doesn't affect all models in game, so only use ssbh_lib_json if you're having issues.

**Closed** 2022-08-20 20:48 UTC
Labels: bug, ssbh_data
