### ISSUE TITLE
Animations crash on custom boneset

### ISSUE THREAD

**Issue by SushiiZ** [ScanMountGoat/ssbh_editor#10] opened 2022-06-19 01:30 UTC
Trying to load animations on a custom boneset with custom meshes and all new bone and mesh names crashes, can send files in DMs on discord if needed

**Comment by ScanMountGoat** [comment] 2022-06-19 03:35
You can upload the files in a zip on github. I can't reproduce this on my end without the files.

**Comment by SushiiZ** [comment] 2022-06-19 05:16
Didn’t want to post em publicly as they’re for a big project I’ve been working on

**Comment by ScanMountGoat** [comment] 2022-06-19 21:43
Try saving the nusktb in ssbh_editor and see if you get any errors. You can also try swapping out the custom files with the unmodified files one by one to figure which file is causing the crash.

**Comment by SushiiZ** [comment] 2022-06-19 22:04
Alright sounds good, does ssbh editor do bone reordering with extra bones?

**Comment by ScanMountGoat** [comment] 2022-06-19 22:27
You need to reorder the bones before exporting the nusktb from Blender or StudioSB. There won't be any visual differences in ssbh_editor if the bones are reordered. If you think this would be helpful to have in ssbh_editor, you can make a new issue for a feature request.

**Comment by SushiiZ** [comment] 2022-06-19 22:35
Reordering them in the nusktb to match the hierarchy (that shows in blender) is what I meant, since studiosb and the blender plugin don’t deal with reordering them, but it’s vital for them to animate properly ingame, And alright, will do

**Comment by SushiiZ** [comment] 2022-06-19 22:58
https://drive.google.com/file/d/13Q2ewrsuMl4wV1Wmnw2yrtZtFHxqWIrU/view?usp=sharing 

here are the files, custom animations work fine on vanilla models

**Comment by ScanMountGoat** [comment] 2022-06-20 01:27
This will be fixed on the next release.

Just as a heads up you have some very large textures files despite only being 512x512. You should be able to disable padding in Switch Toolbox. You may need to replace an existing 512x512 BC7 texture since Toolbox doesn't have very accurate size calculations.

**Closed** 2022-06-20 01:27 UTC

**Comment by SushiiZ** [comment] 2022-06-20 02:07
Haha yeahhh, I fixed those a while ago before my harddrive died, never had the chance to copy em over from that harddrive

Thank you,
Logan
